### ISSUE TITLE
Use of 1300 123 456 as a holding number is live and owned by others - please remove

### ISSUE THREAD

**Issue by Barya7** [healthgovau/health-design-system#39]
Refer https://designsystem.health.gov.au/components/detail/inline-reference--contact.html

Holder number 1300 123 456 is live and in use.

Please remove 1300 123 456 and be aware that all numbers are owned or licenced by the Australian Communications and Media Authority (ACMA) and 1300, 1800 and local numbers should not be used as holder numbers.

**Comment by dlm78** [comment]
Thank you for raising. All instances of the number have been removed.
