### ISSUE TITLE
mandelbrot-healthgovau failing to fetch

### ISSUE THREAD

**Issue by honzapara** [healthgovau/health-design-system#41]
Hi,

recently I found the problem inside of package.json where is the dependency on mandelbrot-healthgovau.
However the following address is wrong: `"mandelbrot-healthgovau": "git+ssh://git@github.com/healthgovau/mandelbrot-healthgovau.git#1.0.0" `. The `npm install` get stuck when is trying to fetch the package. If you try to `git clone git@github.com/healthgovau/mandelbrot-healthgovau.git#1.0.0` it will result with `fatal: repository 'git@github.com/healthgovau/mandelbrot-healthgovau.git#1.0.0' does not exist`.

### Solution

Change `"mandelbrot-healthgovau": "git+ssh://git@github.com/healthgovau/mandelbrot-healthgovau.git#1.0.0",` to
`"mandelbrot-healthgovau": "https://github.com/healthgovau/mandelbrot-healthgovau.git#1.0.0",`.

This works for me OK.

**Comment by dlm78** [comment]
Thank you for reporting and fixing this. The PR has been merged.
